changelog:
  categories:
    - title: Enhencement
      labels:
        - ehancement
    - title: Bug Fix
      labels:
        - Bug
        - Fix
  exclude:
    labels:
      - dependency
    authors:
      - dependabot[bot]